routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FrontendController\HomeController@index")->name('home');


Route::get('/login', "AuthController\LoginController@index")->name('login-index');
Route::post('/login', "AuthController\LoginController@login")->name('login');

Route::get('/signup', "AuthController\SignupController@index")->name('signup-index');
Route::post('/signup', "AuthController\SignupController@signup")->name('signup');

Route::get('/logout', "AuthController\LoginController@logout")->name('logout');

Route::middleware('auth')->group(function () {

	Route::resource('todos', 'ToDoListController');

	Route::post('/switch', "ToDoListController@switch")->name('todo.switch');

	Route::get('/activity', "ActivityController@index")->name('activity.index');

	Route::get('/favorite', "FavoriteController@index")->name('favorite.index');

	Route::get('/favorite/get', "FavoriteController@getToRedis")->name('favorite.get');

	Route::get('/favorite/set/{user_id}/{item}', "FavoriteController@setToRedis")->name('favorite.set');

	Route::get('/favorite/clear', "FavoriteController@clear")->name('favorite.clear');


});

resources/views/frontend_v1/include/footer.blade.php
Made by <a href="https://github.com/thanhryot" target="_blank"><i>Thanh Ryot</i></a> with ❤️ for Laravel!

resources/views/frontend_v1/include/form-error.blade.php
@if ($errors->any())
    <div style="color:red">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/frontend_v1/include/header.blade.php
<div class="pt-3">
	@if(auth()->user())

	Hello, <b>{{ auth()->user()->name }}</b> |

	<a href="{{ route('todos.index') }}">Todo Lists</a> |
	
	<a href="{{ route('activity.index') }}">Activities Log</a> |

	<a href="{{ route('favorite.index') }}">My Favorite</a> |

	<a href="{{ route('logout') }}">Logout</a>
	@else

	<a href="{{ route('login') }}">Login</a> | <a href="{{ route('signup') }}">Signup</a>

	@endif
</div>