routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FrontendController\HomeController@index")->name('home');


Route::get('/login', "AuthController\LoginController@index")->name('login-index');
Route::post('/login', "AuthController\LoginController@login")->name('login');

Route::get('/signup', "AuthController\SignupController@index")->name('signup-index');
Route::post('/signup', "AuthController\SignupController@signup")->name('signup');

Route::get('/logout', "AuthController\LoginController@logout")->name('logout');

Route::middleware('auth')->group(function () {

	Route::resource('todos', 'ToDoListController');

	Route::post('/switch', "ToDoListController@switch")->name('todo.switch');

	Route::get('/activity', "ActivityController@index")->name('activity.index');

	Route::get('/favorite', "FavoriteController@index")->name('favorite.index');

	Route::get('/favorite/get', "FavoriteController@getToRedis")->name('favorite.get');

	Route::get('/favorite/set/{user_id}/{item}', "FavoriteController@setToRedis")->name('favorite.set');

	Route::get('/favorite/clear', "FavoriteController@clear")->name('favorite.clear');


});

resources/views/frontend_v1/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <title>TodoApp</title>

        <link rel="stylesheet" href="/vendor/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            {{-- header --}}
                
                @include('frontend_v1.include.header')

            {{-- end header --}}


            {{-- main body--}}

                <hr>

                @if(auth()->check())
                    <div class="mb-3"><a href="{{ route('todos.create') }}" class="btn btn-success">Add new todo</a></div>
                @endif
                
                @yield('main')
                
                <hr>
            {{-- end main body --}}

            {{-- footer --}}

                @include('frontend_v1.include.footer')

            {{-- end footer --}}
            <script src="/vendor/jquery.min.js"></script>

            @stack('scripts')
        </div>        
    </body>
</html>