routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FrontendController\HomeController@index")->name('home');


Route::get('/login', "AuthController\LoginController@index")->name('login-index');
Route::post('/login', "AuthController\LoginController@login")->name('login');

Route::get('/signup', "AuthController\SignupController@index")->name('signup-index');
Route::post('/signup', "AuthController\SignupController@signup")->name('signup');

Route::get('/logout', "AuthController\LoginController@logout")->name('logout');

Route::middleware('auth')->group(function () {

	Route::resource('todos', 'ToDoListController');

	Route::post('/switch', "ToDoListController@switch")->name('todo.switch');

	Route::get('/activity', "ActivityController@index")->name('activity.index');

	Route::get('/favorite', "FavoriteController@index")->name('favorite.index');

	Route::get('/favorite/get', "FavoriteController@getToRedis")->name('favorite.get');

	Route::get('/favorite/set/{user_id}/{item}', "FavoriteController@setToRedis")->name('favorite.set');

	Route::get('/favorite/clear', "FavoriteController@clear")->name('favorite.clear');


});

resources/views/frontend_v1/pages/todos/create.blade.php
@extends('frontend_v1.app')


@section('main')
<div class="row">
	<div class="col-md-8">
		<form action="{{ route('todos.store') }}" method="POST" class="form-group">
			{{ csrf_field() }}
			<label for="item">Add Item: </label>
			<input type="text" class="form-control" placeholder="Enter the to-do list..." name="item"><br>
			<button type="submit" class="btn btn-success">Add</button>
		</form>
	</div>
</div>


@endsection

resources/views/frontend_v1/pages/todos/edit.blade.php
@extends('frontend_v1.app')


@section('main')
<div class="row">
	<div class="col-md-8">
		<form class="form-group" action="{{ route('todos.update', ['todo' => $todo->id]) }}" method="POST">
			 {{ method_field('PUT') }}
			{{ csrf_field() }}
			<label for="item">Item: </label>
			<input type="text" class="form-control" value="{{ $todo->item }}" name="item">
			<br>
			<button type="submit" class="btn btn-info">Update</button>
		</form>
	</div>
</div>
@endsection

resources/views/frontend_v1/pages/todos/index.blade.php
@extends('frontend_v1.app')


@section('main')

@if(count($todo_lists))
<table class="table table-hover table-striped table-responsive">
	<tr>
		<th class="w-25">Order</th>
		<th class="w-25">Item</th>
		<th class="w-25">Status</th>
		<th class="w-25">Action</th>
	</tr>

	@foreach($todo_lists as $todo_list)
	<tr>
		<td>{{ $loop->iteration }}</td>
		<td><a href="{{ route('todos.show', ['todo' => $todo_list->id]) }}">{{ $todo_list->item }}</a></td>
		<td>
			<input class="todo-check" data-id="{{ $todo_list->id }}" type="checkbox" @if($todo_list->is_done) checked @endif>
		</td>
		<td>
			<form style="display: inline-block;" action="{{ route('todos.edit',['todo' => $todo_list->id]) }}">
				<input type="submit" value="Edit" class="btn btn-small btn-info">
			</form>

			<form style="display: inline-block;" action="{{ route('todos.destroy',['todo' => $todo_list->id]) }}" method="POST">
	 			{{ method_field('DELETE') }}
				{{ csrf_field() }}
				<input type="submit" value="Delete" class="btn btn-small btn-danger">
			</form>
			<a href="{{ route('favorite.set', ['user_id' => auth()->id(), 'item' => $todo_list->item]) }}" class="btn btn-warning">Favorite</a>
		</td>
	</tr>

	@endforeach
</table>

{{-- pagination --}}
{{ $todo_lists->links() }}

@endif

@endsection

@push('scripts')
<script src="/js/app.js"></script>
@endpush

resources/views/frontend_v1/pages/todos/show.blade.php
@extends('frontend_v1.app')


@section('main')

<h1>{{ $todo->item }}</h1>
@if($todo->is_done)

<p class="text-success">Finished !!</p>
@else

<p class="text-warning">Unfinished !!</p>

@endif


@endsection